In [1]:
import sys
from pathlib import Path

# 1. Определяем корень проекта
# (подбираем количество .parent, чтобы попасть в max_projects)
project_root = Path.cwd().parent

# 2. Добавляем корень в пути поиска модулей
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

# 3. Проверяем, что путь добавлен
print(f"✅ Project root: {project_root}")
print(f"✅ Sys path: {sys.path[:3]}...")

✅ Project root: c:\Users\123\Desktop\start_vector
✅ Sys path: ['c:\\Users\\123\\Desktop\\start_vector', 'C:\\Python314\\python314.zip', 'C:\\Python314\\DLLs']...

In [2]:
from src_oop.core.database import Database
from src_oop.jobs.unit.queries import query_adv_spend
from src_oop.jobs.unit.config import unit_gs
from src_oop.jobs.fin_reports_analyze.repository import FinReportsAnalyze
from src_oop.core.my_gspread import GoogleTabs

import pandas as pd

In [6]:
query = """
    SELECT c.target_vendor_code,
       c.target_account,
       c.local_vendor_code,
       a.nm_id,
       cd.subject_name,
       cd.wb_name,
       cp.purchase_price,
       DATE(c.updated_at) as date
FROM card_clone_job c
LEFT JOIN article a
    ON c.target_vendor_code = a.vendor_code
    AND c.target_account = a.account
LEFT JOIN (
    SELECT AVG(cp.purchase_price) AS purchase_price,
           cp.local_vendor_code,
           cp.date
        FROM cost_price cp
        WHERE cp.date >= '2026-04-20'
        GROUP BY cp.local_vendor_code, cp.date
    ) cp
    ON c.local_vendor_code = cp.local_vendor_code
    AND DATE(c.updated_at) = cp.date
LEFT JOIN card_data cd
    ON a.nm_id = cd.article_id
WHERE DATE(c.updated_at) >= '2026-04-20'
AND a.nm_id IS NOT NULL;
       """
analyze = FinReportsAnalyze()
df = analyze.get_df_from_db(query)

In [7]:
df['target_account'] = df['target_account'].str.capitalize()
df.head()

,target_vendor_code,target_account,local_vendor_code,nm_id,subject_name,wb_name,purchase_price,date
0,wild1789,Вектор8159,wild1789,978400416,Тренажеры,Виброплатформа тренажер для похудения,2400.0,2026-04-20
1,wild1594,Вектор8159,wild1594,978400431,Маркеры,Маркеры для скетчинга набор двусторонних флома...,848.0,2026-04-20
2,wild1639,Вектор8159,wild1639,978400329,Контейнеры из полимеров,Ланч бокс герметичный для еды складной силикон...,451.0,2026-04-20
3,wild1605,Вектор8159,wild1605,978400381,Казаны,Казан чугунный с крышкой узбекский для плова 1...,1172.0,2026-04-20
4,wild1604,Вектор8159,wild1604,978400411,Казаны,Казан чугунный с крышкой узбекский для плова 1...,1031.0,2026-04-20

In [9]:
df[df['local_vendor_code'] == 'wild1789']

,target_vendor_code,target_account,local_vendor_code,nm_id,subject_name,wb_name,purchase_price,date
0,wild1789,Вектор8159,wild1789,978400416,Тренажеры,Виброплатформа тренажер для похудения,2400.0,2026-04-20
400,wild1789,Вектор4135,wild1789,979945817,Тренажеры,Виброплатформа тренажер для похудения,2400.0,2026-04-21
874,wild1789,Старт9900,wild1789,979946853,Тренажеры,Виброплатформа тренажер для похудения,2400.0,2026-04-21
1094,wild1789,Старт5020,wild1789,979946251,Тренажеры,Виброплатформа тренажер для похудения,2400.0,2026-04-21

In [10]:
filtered_df = df[~(df['local_vendor_code'] != df['target_vendor_code']) & (df['local_vendor_code'].str.contains('wild', na=False))]
filtered_df.shape

(1478, 8)

In [11]:
path = "C:\\Users\\123\\Downloads\\filtered_data_30_04_2026.csv"
filtered_df.to_csv(path, index=False)

In [12]:
filtered_df.tail()

,target_vendor_code,target_account,local_vendor_code,nm_id,subject_name,wb_name,purchase_price,date
1512,wild1683,Вектор4135,wild1683,979945273,Тренажеры,Степпер тренажер для ног и ягодиц с эспандерами,1850.0,2026-04-21
1513,wild1563,Вектор8159,wild1563,978400826,Вентиляторы,Вентилятор настольный с увлажнителем воздуха п...,285.0,2026-04-20
1514,wild345,Вектор8159,wild345,978401458,Наборы для специй,Баночки для специй и чая с ложками,150.0,2026-04-20
1515,wild355,Вектор8159,wild355,978399610,Наборы кухонных принадлежностей,Набор кухонных принадлежностей с ножами 19в1,1022.0,2026-04-20
1516,wild1398,Старт5020,wild1398,979947147,Триммеры садовые,Триммер садовая газонокосилка,876.0,2026-04-21

In [ ]:
'6bbd699d-ef97-11f0-84f4-50ebf6b2ce7c',
'5bad2e15-ef97-11f0-84f4-50ebf6b2ce7c',
'86de165a-efa1-11f0-84f4-50ebf6b2ce7c',
'6451220a-ef97-11f0-84f4-50ebf6b2ce7c',
'd2b67fe6-efa2-11f0-84f4-50ebf6b2ce7c',
'5bad2da9-ef97-11f0-84f4-50ebf6b2ce7c',
'5bad2efc-ef97-11f0-84f4-50ebf6b2ce7c',
'4d399418-efac-11f0-84f4-50ebf6b2ce7c',
'4d3993ac-efac-11f0-84f4-50ebf6b2ce7c',
'6451218c-ef97-11f0-84f4-50ebf6b2ce7c',
'3fbf9806-efa1-11f0-84f4-50ebf6b2ce7c',
'6bbd673b-ef97-11f0-84f4-50ebf6b2ce7c',
'4d3992d4-efac-11f0-84f4-50ebf6b2ce7c',
'4d399124-efac-11f0-84f4-50ebf6b2ce7c',
'5bad2d3d-ef97-11f0-84f4-50ebf6b2ce7c',
'6bbd67a7-ef97-11f0-84f4-50ebf6b2ce7c',
'645120fc-ef97-11f0-84f4-50ebf6b2ce7c',
'6bbd6a1b-ef97-11f0-84f4-50ebf6b2ce7c',
'4d399340-efac-11f0-84f4-50ebf6b2ce7c',
'6bbd6813-ef97-11f0-84f4-50ebf6b2ce7c',
'64511ebc-ef97-11f0-84f4-50ebf6b2ce7c',
'4d399484-efac-11f0-84f4-50ebf6b2ce7c',
'6bbd6a87-ef97-11f0-84f4-50ebf6b2ce7c',
'5bad2e90-ef97-11f0-84f4-50ebf6b2ce7c',
'4d3991fc-efac-11f0-84f4-50ebf6b2ce7c',
'64511f94-ef97-11f0-84f4-50ebf6b2ce7c',
'6bbd66cf-ef97-11f0-84f4-50ebf6b2ce7c',
'6451207e-ef97-11f0-84f4-50ebf6b2ce7c',
'6bbd6931-ef97-11f0-84f4-50ebf6b2ce7c',
'd2b6814b-efa2-11f0-84f4-50ebf6b2ce7c'